site_name: "gosrvlib"
site_description: "gosrvlib Go Library documentation"
repo_url: https://github.com/Vonage/gosrvlib
edit_uri: edit/main/
repo_name: "GitHub"
docs_dir: "doc"
markdown_extensions:
  - pymdownx.snippets:
      base_path: [".", ".."]
plugins:
  - techdocs-core
nav:
  - Introduction: 'README.md'
