site_name: "gosrvlib"
site_description: "Documentation on the gosrvlib library"
repo_url: https://github.com/nexmoinc/gosrvlib
edit_uri: edit/main/
repo_name: "GitHub"
docs_dir: .
plugins:
  - techdocs-core
  - same-dir
nav:
  - "README.md"
