FROM golang
ENV PATH=/root/.local/bin:$PATH
RUN apt-get update \
&& apt-get -y install \
devscripts \
fakeroot \
debhelper \
pkg-config \
alien \
rpm \
dh-make \
dh-golang \
upx-ucl \
python3 \
python3-pip \
&& pip3 install --upgrade --user jsonschema
