// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vonage/gosrvlib/pkg/httpserver (interfaces: Binder)
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package httpserver -destination ./mock_test.go . Binder
//

package httpserver

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBinder is a mock of Binder interface.
type MockBinder struct {
	ctrl     *gomock.Controller
	recorder *MockBinderMockRecorder
	isgomock struct{}
}

// MockBinderMockRecorder is the mock recorder for MockBinder.
type MockBinderMockRecorder struct {
	mock *MockBinder
}

// NewMockBinder creates a new mock instance.
func NewMockBinder(ctrl *gomock.Controller) *MockBinder {
	mock := &MockBinder{ctrl: ctrl}
	mock.recorder = &MockBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinder) EXPECT() *MockBinderMockRecorder {
	return m.recorder
}

// BindHTTP mocks base method.
func (m *MockBinder) BindHTTP(ctx context.Context) []Route {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindHTTP", ctx)
	ret0, _ := ret[0].([]Route)
	return ret0
}

// BindHTTP indicates an expected call of BindHTTP.
func (mr *MockBinderMockRecorder) BindHTTP(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindHTTP", reflect.TypeOf((*MockBinder)(nil).BindHTTP), ctx)
}
