.\" Manpage for gosrvlibexample.
.TH GOSRVLIBEXAMPLE "1" "2020" "gosrvlibexample" "User Commands"
.SH NAME
gosrvlibexample \- gosrvlibexampleshortdesc
.SH DESCRIPTION
gosrvlibexamplelongdesc
.SS "Usage:"
.IP
gosrvlibexample [flags]
gosrvlibexample [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-f\fR, \fB\-\-logFormat\fR=\fI10\fR: Logging format: CONSOLE, JSON
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
.PP
Use "gosrvlibexample [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Author (dev@example.com)
.SH COPYRIGHT
(c) 2020 Author
