.\" Manpage for srvxmplname.
.TH SRVXMPLNAME "1" "2020" "srvxmplname" "User Commands"
.SH NAME
srvxmplname \- srvxmplshortdesc
.SH DESCRIPTION
srvxmpllongdesc
.SS "Usage:"
.IP
srvxmplname [flags]
srvxmplname [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-f\fR, \fB\-\-logFormat\fR=\fI10\fR: Logging format: CONSOLE, JSON
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
.PP
Use "numapi [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Vonage (ops@nexmo.com)
.SH COPYRIGHT
(c) 2020 Vonage
