# https://golangci-lint.run/usage/configuration/
# To get the list of available linters: ./target/binutil/golangci-lint help linters

run:
  issues-exit-code: 1
  tests: true
  timeout: 5m
  skip-dirs-use-default: true

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  formats: colored-line-number

linters-settings:
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true
  gocognit:
    min-complexity: 10
  gocyclo:
    min-complexity: 10
  gofmt:
    simplify: true
  misspell:
    locale: US
  whitespace:
    multi-if: false   # Enforces newlines (or comments) after every multi-line if statement
    multi-func: false # Enforces newlines (or comments) after every multi-line function signature
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/Vonage
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr

issues:
  exclude-dirs:
    - .github
    - .githook
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
  #fix: true

linters:
  enable-all: true
  disable:
    - depguard    # Go linter that checks if package imports are in a list of acceptable packages [fast: true, auto-fix: false]
    - execinquery    # execinquery is a linter about query string checker in Query function which reads your Go src files and warning it finds [fast: false, auto-fix: false]
    - exhaustruct    # Checks if all structure fields are initialized [fast: false, auto-fix: false]
    - err113    # Go linter to check the errors handling expressions [fast: false, auto-fix: false]
    - gomnd    # An analyzer to detect magic numbers. [fast: true, auto-fix: false]
    - gomoddirectives    # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod. [fast: true, auto-fix: false]
    - ireturn    # Accept Interfaces, Return Concrete Types [fast: false, auto-fix: false]
    - lll    # Reports long lines [fast: true, auto-fix: false]
    - mnd   # An analyzer to detect magic numbers. [fast: true, auto-fix: false]
    - musttag    # enforce field tags in (un)marshaled structs [fast: false, auto-fix: false]
    - nlreturn    # nlreturn checks for a new line before return and branch statements to increase code clarity [fast: true, auto-fix: false]
    - promlinter    # Check Prometheus metrics naming via promlint [fast: true, auto-fix: false]
    - tagliatelle    # Checks the struct tags. [fast: true, auto-fix: false]
    - testpackage    # linter that makes you use a separate _test package [fast: true, auto-fix: false]
    - varnamelen    # checks that the length of a variable's name matches its scope [fast: false, auto-fix: false]
    - exportloopref # deprecated
