version: '3.3'

services:
  gosrvlibexample_integration:
    container_name: gosrvlibexample_integration
    build:
      context: .
      dockerfile: test.integration.Dockerfile
    environment:
      DEPLOY_ENV: "int"
    depends_on:
      - gosrvlibexample
      - gosrvlibexample_smocker_ipify
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize

  gosrvlibexample:
    image: gosrvlibexample/gosrvlibexample:latest
    container_name: gosrvlibexample
    restart: always
    env_file:
      - target/gosrvlibexample.integration.env
    entrypoint: [
        "/usr/bin/dockerize",
        "-wait", "tcp://gosrvlibexample_smocker_ipify:8081",
        "/usr/bin/gosrvlibexample"
    ]
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize

  gosrvlibexample_smocker_ipify:
    container_name: gosrvlibexample_smocker_ipify
    image: thiht/smocker
