FROM golang:1.19
ENV PATH=/root/.local/bin:$PATH
RUN apt update \
&& apt -y install \
devscripts \
fakeroot \
debhelper \
pkg-config \
alien \
rpm \
dh-make \
dh-golang \
upx-ucl \
python3 \
python3-pip \
&& pip3 install --upgrade --user jsonschema schemathesis httpx \
&& curl --location https://github.com/ovh/venom/releases/download/v1.0.1/venom.linux-amd64 > /usr/bin/venom \
&& chmod ug+x /usr/bin/venom
