FROM golang:1.17
ENV PATH=/root/.local/bin:$PATH
RUN apt update \
&& apt -y install \
devscripts \
fakeroot \
debhelper \
pkg-config \
alien \
rpm \
dh-make \
dh-golang \
upx-ucl \
python3 \
python3-pip \
&& pip3 install --upgrade --user jsonschema schemathesis
ADD https://github.com/ovh/venom/releases/download/v1.0.0-rc.6/venom.linux-amd64 /usr/bin/venom
RUN chmod ug+x /usr/bin/venom
