name: confluence

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'Vonage/gosrvlib'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with: { ref: main }
      - name: setup go build environment
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: install publishing tool
        run: go install github.com/kovetskiy/mark@latest
      - name: publish docs
        run: |
          touch ~/.config/mark || true
          mark -u ${{ secrets.CONFLUENCE_USER }} -p ${{ secrets.CONFLUENCE_TOKEN }} -b ${{ secrets.CONFLUENCE_URL }} -f README.md
