name: confluence

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with: { ref: main }
      - name: setup go build environment
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: install publishing tool
        run: go install github.com/kovetskiy/mark@latest
      - name: publish docs
        run: mark -u ${{ secrets.CONFLUENCE_USER }} -p ${{ secrets.CONFLUENCE_TOKEN }} -b ${{ secrets.CONFLUENCE_URL }} -f README.md
